---
---

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
listExample[[1]]
listExample[[2]]
```

```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap
length(tainanSportsMap)
tainanSportsMap[[500]]
```

```{r}
length(tainanSportsMap)
tainanSportsMap[[500]]
```

```{r}
names(listExample)
```

```{r}
listExample$student
listExample$`學期`
```

```{r}
str(listExample$`學期`)
```

```{r}
listExample[["student"]]
listExample$student
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
newTaipeiCityVaccine[["result"]]
str(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
names(newTaipeiCityVaccine)

str(newTaipeiCityVaccine[[2]], max.level = 1)
```

```{r}
vectorExample = c("小明", "小英", "大雄")
vectorExample[c(1,3)]
vectorExample[c(3,2,1)]
```

```{r}
str(listExample, max.level = 1)

str(listExample[c(1,2)], max.level = 1)
str(listExample[c(2,1)], max.level = 1)
```

```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap


str(tainanSportsMap, max.level = 1)
str(tainanSportsMap[c(1,340,1076)], max.level = 1)
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
str(taipeiNightMarkets, max.level = 1)
taipeiNightMarkets[c("寧夏觀光夜市", "華西觀光夜市", "廣州街觀光夜市")]
```

```{r}
vectorExample
vectorExample[c(T,T,F)]
```

```{r}
str(listExample)
str(listExample[c(F,T)])
str(listExample[c("學期")])
str(listExample[c(T,T)])
```

```{r}
names(taipeiNightMarkets)
selectedMarkets <- c(T,F,F,F,T,F,F,F,F,T,F,F,F,T)
str(taipeiNightMarkets[selectedMarkets])
selectedMarkets <- rep(F, 14)
selectedMarkets[c(1,5,10,14)] <- TRUE
str(taipeiNightMarkets[selectedMarkets], max.level = 1)
```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]
```

```{r}
str(listExample, max.level = 3)
str(get1, max.level = 1)
str(get2, max.level = 1)
```

```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
numVector[c(1,4)][[1]]
```

```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")

econOnly <- c(T,T,F,F,T)
names[econOnly];gender[econOnly]
econFemaleOnly <- gender[econOnly][c(T,T,F)];econFemaleOnly
names[c(econOnly)][c(T,T,F)]
```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]
```

```{r}
str(get1)
```

```{r}
str((get2))
```

```{r}
get1[["108-1"]][[1]][["teacher"]]
listExample[["學期"]]$`108-1`[[1]]$teacher
listExample["學期"][[1]][["108-1"]][[1]]$teacher
```

```{r}
a <- c("1", "b", "TRUE")
a[[2]] <- "c"
a[[4]] <- "7"
a[c(5,6)] <- c("J", "K")

a[[7]] <- "Johnson"
a <- c(a, "Mary")
```



```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
list1[[1]]$birthday <- ymd("1997-03-21")
list1[[2]] <- list(
  name = "Mary",
  birthday = ymd("1998-08-24")
)
list1[[2]]$status <- c(height = 163, weight = 45)
list1[[1]]$status[["height"]] <- 176
```

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)


# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )

listExample[[2]]$`108-1`[[2]] <- list(
  name = "產業經濟學",
  teacher = "Wen",
  grade = 88
)
# 有多少位置可選：
length(listExample)
str(listExample)
```

```{r}
a
a[-c(1,3)] -> a
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )

list1[[1]] <- list1[[1]][-3]
list1[[2]] <- list1[[2]][-c(3,5)]
str(list1)
```

```{r}
str(list1)
list1[[2]][c(1,2)] <- NULL
str(list1)
```

```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike
```

```{r}
newTaipeiYouBike[[1]][-c(1,2,3)] -> newTaipeiYouBike[[1]]
newTaipeiYouBike[[1]][c(1,2,3)] <- NULL

str(newTaipeiYouBike[[1]])
```

```{r}
a <- c(2, 3, 5)
b <- c(4, 1, 3)
```

```{r}
a+b
a%%b
a**b
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```

```{r}
library(readr)
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
str(transcript100to103)
```

```{r}
example$birthday
class(example$birthday)
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```

```{r}
source("https://www.dropbox.com/s/16h6ggua6qtydci/exchangeRate.R?dl=1")
```

```{r}
install.packages("readr")
```

```{r}
str(exchangeRate)
```

```{r}
# 只要1998年1月（含）以後的
library(lubridate)
pick_after98_01 <-
  exchangeRate$`期間` >= ymd("1998-01-01")
exchangeRate_after98 <-
  list(
    `期間`=exchangeRate$`期間`[pick_after98_01],
    `幣別`=exchangeRate$`幣別`[pick_after98_01],
    `匯率`=exchangeRate$`匯率`[pick_after98_01]
    
  )
```

```{r}
print(example[c("name","allowance")])

pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
str(example)
```

```{r}
levels(example$allowance)
example$allowance <- ordered(example$allowance)
class(example$allowance)
```

```{r}
install.packages('curl')
jsonlite::fromJSON("https://www.dropbox.com/s/3uijub7xheib405/list_victimAges_female.json?dl=1", simplifyDataFrame = F) -> list_victimAges_female
str(list_victimAges_female)
View(list_victimAges_female$`數目`)
sum(list_victimAges_female$`數目`)
sum(list_victimAges_female$`數目`, na.rm=T)
```

```{r}
list_victimAges_female$`數目` <-
  as.integer(list_victimAges_female$`數目`)
list_victimAges_female$`年齡層` <- 
  as.factor(list_victimAges_female$`年齡層`)
str(list_victimAges_female)
```

```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
```

```{r}
str(transcript100to103)
```

```{r}
# 各學屆2年級人數
table(transcript100to103$`學屆`)
pick_above85 <-
  transcript100to103$`成績` > 85
# 各學屆2年級成績大於85年數
table(transcript100to103$`學屆`[pick_above85])
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
str(example)
pick_above170 <- example$height >= 170
pick_bloodB <- example$bloodType == "B"
pick_loveFood <- 
  stringr::str_detect(example$hobby,"美食")
pick_na <- is.na(example$weight)
pick_after98 <- 
  example$birthday >= lubridate::ymd("1998-01-01")
set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- 
  example$residence %in% set_TaipeiMetro
```

```{r}
str(example[c("name","hobby","bloodType")])

example$name[
    pick_loveFood & pick_bloodB
  ]
```

```{r}
example[c("name","birthday","residence")]

example$name[
  pick_after98 | !pick_fromTaipeiMetro
]
```

```{r}
example$name[
  pick_after98 & pick_fromTaipeiMetro & pick_bloodB
]
```

```{r}
pick_after98 & pick_fromTaipeiMetro & pick_bloodB
```

```{r}
install.packages("stringr")
install.packages("glue")
library(stringr)
library(glue)
```

```{r}
str_sub(
  c("410873002", "410873060"),
  5, 6)
```

```{r}
lubridate::ymd(
  c(
    "民國2019年12月05日",
    "馬丁2019的12課05muydifícil",
    "助教2019Emily12解說05真棒",
    "2019R12課程05すごい",
    "R程式2019的12期中考05とても変態"
  )
)
```

```{r}
str_extract_all(
  c("民國108年12月5日","民國98年10月5日"),
  "(?<=民國)[0-9]{2,3}(?=年)"
) # 回傳list 

str_extract(
  c("民國108年12月5日","民國98年10月5日"),
  "(?<=民國)[0-9]{2,3}(?=年)"
) # 回傳vector 
```

```{r}
install.packages("htmlwidgets")
studentIds <- c("410873029","410773005","410772035","410562123")
# 取出學號中的入學屆為107或108
str_view_all(studentIds,"(107|108)")

str_view_all(studentIds, "107|108") # 可不寫()

# 是否來自107或108學屆
str_detect(studentIds, "107|108")
```

```{r}
Ids <- c("A283743192","B829103720","A10920402","C291022384")

str_view_all(Ids, "[AC]")
str_detect(Ids, "[AC]") # 偵測 出現A、C

str_extract(Ids,"[A-Z]") # 取出 A-Z的字元
```

```{r}
strip1 <- "[0-9]"
strip2 <- "(櫻桃|777|紅心)" # 字群組合strip因為等下放中間所以用()括起來
strip3 <- "[A-Z]"
myRegexSlotMachine <- paste0(strip1,strip2,strip3)
print(myRegexSlotMachine)
```

```{r}
claimA <- "我得到A檸檬99"
claimB <- "我的是7777Z"
claimC <- "我玩了兩次，一次是7蘋果H，另一次是5紅心J"
# 顯示吻合的出象
str_view(
  c(claimA,claimB,claimC),
  pattern=myRegexSlotMachine
)
# 是否有吻合的出象
str_detect(
  c(claimA,claimB,claimC),
  pattern=myRegexSlotMachine
)
```

```{r}
headline <- "資科系的謝陳官乃飛鳶書院三大名師，其中謝無雙的策略運算，陳大器的數理資科學，及官求敗的運算成本更是打通演算思維任督二脈的三大好課。書院目前有陳一、陳二、陳三四這三名學生。"
```

```{r}
# 顯示所有符合規則的
str_view_all(headline, "謝陳官") # 固定字組
str_count(headline,"謝陳官")

str_view_all(headline, "[謝陳官]") # 有1個strip: 出象有3個可能字元 
str_count(headline, "[謝陳官]")

str_view_all(headline, "謝無雙|官求敗") # 有1個strip，出象有2個字組 
str_count(headline, "謝無雙|官求敗")

str_view_all(headline, "陳[^官]") # 固定字元＋有1個strip： 出象為排官的字元
str_count(headline, "陳[^官]")
```

```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓'
  )

strip1 <- strip2 <- strip3 <- "[0-9]"
strip4 <- "號"
myRegexSlotMachine <- paste0(strip1,strip2,strip3,strip4)
print(myRegexSlotMachine)
str_extract(addresses,myRegexSlotMachine)
```

```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')
```

```{r}
myRegexSlotMachine <- "[0-9]+號"
print(myRegexSlotMachine)
str_view_all(addresses,myRegexSlotMachine)
str_extract(addresses,myRegexSlotMachine)

str_view_all(addresses,"[0-9]+") # 樓號也會選到
```

```{r}
phrase <- c("唧唧复唧唧")
```

```{r}
# 目標是前面的唧唧
target_regex <- "唧唧"
pattern <- glue::glue("^{target_regex}")
print(pattern)
str_view(phrase, pattern) 
```

```{r}
# 目標是後面的唧唧
target_regex2 <- "唧唧"
pattern <- glue::glue("{target_regex2}$")
print(pattern)
str_view(phrase, pattern) 
```

```{r}
twDate <-  c("民國108年12月5日","民國98年10月5日")

library(stringr)
# 準備regex: 
## 取出：「前有」民國，「後有」年的「數字」「們」
## "(?<={A_regex}){target_regex}(?={B_regex})"

target_regex <- "[0-9]+"
A_regex <- "民國"
B_regex <- "年"

regex_pattern <- glue::glue(
  "(?<={A_regex}){target_regex}(?={B_regex})"
  )

print(regex_pattern)

## 如果同學已經很熟就可以直接寫
regex_pattern <-
  "(?<=民國)[0-9]+(?=年)"

# 取出民國年，計算西元年
year <- 
  str_extract(
    twDate,
    regex_pattern)
westernYear <- as.integer(year)+1911

# 替換民國xx年的xx成西元年數字
str_replace(
  twDate,
  regex_pattern,  # 要換掉的文字
  as.character(westernYear) # 要替換的內容
) -> twDate_reformat
print(twDate_reformat)


lubridate::ymd(twDate_reformat)
```

```{r}
date1 <- "康熙23年5月6日"
regex_pattern1 <- "(?<=康熙)[0-9]+(?=年)"
year <- str_extract(
  date1, regex_pattern1
  )
westernYear1 <- as.integer(year) + 1661
date_reform <-
  str_replace(
    date1,
    regex_pattern1,
    as.character(westernYear1)
  )
datefinal <- lubridate::ymd(date_reform)
class(datefinal)
```

```{r}
char1 <- c("Wild","Apple","Donald","May","Avocada") 
factor1 <- factor(char1)
levels(factor1)
```

```{r}
library(stringr)
char2 <- c("蔡英文","習近平","Donald Trump","蔡頭") 
factor2 <- factor(char2)
levels(factor2)

sort(
  str_sub(char2,1,1)
)
sort(
  str_sub(char2,2,2)
)
```

```{r}
Sys.getlocale("LC_COLLATE")
```

```{r}
jsonlite::fromJSON("https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.json") -> covid19
```

```{r}
# 不可排序類別：性別、縣市、是否境外移入
covid19$`縣市` <- 
  factor(covid19$`縣市`)
covid19$`性別` <-
  factor(covid19$`性別`)
covid19$`是否為境外移入` <-
  factor(
    covid19$`是否為境外移入`
  )
```

```{r}
# 可排序類別資料：年齡層
covid19$`年齡層` <-
  factor(
    covid19$`年齡層`,
    ordered=TRUE
  )
```

```{r}
levels(covid19$`縣市`)
levels(covid19$`性別`)
levels(covid19$`是否為境外移入`)
covid19$`年齡層`
levels(covid19$`年齡層`)
```

```{r}
levels(covid19$`性別`)
covid19$`性別` <- factor(covid19$`性別`, c("男","女"))
levels(covid19$`性別`)
```

```{r}
levels(covid19$`縣市`)
```

```{r}
jsonlite::fromJSON(
  "https://www.dropbox.com/s/jckqryeh5zeat5w/regionPopulation.json?dl=1"
) -> population
unlist(population) -> population
```

```{r}
levels(covid19$`縣市`) # 是名稱字串向量

# 由於population元素值有names，可以用`[名稱字串向量]`取出所要的
levels(covid19$`縣市`) -> levelsInData
population[levelsInData] -> population
print(population)
```

```{r}
population <- sort(population, decreasing=T)
newLevels <- names(population)
newLevels
covid19$`縣市` <-
  factor(
    covid19$`縣市`, levels=newLevels
  )

levels(covid19$`縣市`)
```

```{r}
newlevels1 <- names(sort(table(covid19$`縣市`), decreasing=T))
covid19$`縣市` <-
  factor(
    covid19$`縣市`, newlevels1
  )
levels(covid19$`縣市`)
```

```{r}
levels(covid19$`年齡層`)
```

```{r}
level_names <- levels(covid19$`年齡層`)
startingAges <- stringr::str_extract(
  level_names,
  "^[0-9]+" # regex：開頭的一串數字
)
```

```{r}
# 要numerical class排的才一定對
startingAges <- as.integer(startingAges)
names(startingAges) <- level_names
sort(startingAges) -> startingAges
```

```{r}
covid19$`年齡層` <- 
  factor(
    covid19$`年齡層`, names(startingAges)
  )
levels(covid19$`年齡層`)
```

```{r}
factor1 <- factor(
  c("A","A","C","A","D","F","D","D")
)
factor1

levels(factor1) <- c("優","佳","尚可","普")

factor1
```

```{r}
levels(factor1)[[1]] <- "Excellent"
levels(factor1)[c(3,4)] <- c("C","D")
factor1
```

```{r}
factor1 <- factor(c("新北市","台北市","台中市","彰化市","基隆市","苗栗縣","苗栗縣"))
levels(factor1)
levels(factor1) <- c("中部","北部","北部","中部","北部","中部")
factor1
```

```{r}
factor1 <- factor(c("0-4歲","5-9歲","10歲以上","0-4歲","5-9歲","5-9歲","10歲以上"))
factor1
levels(factor1) <- c("0-9歲","10歲以上","0-9歲")
factor1
```

```{r}
covid19$`地區` <- covid19$`縣市`
levels(covid19$`地區`)
currentLevels <- levels(covid19$`地區`)

# 整併
north_regex <- "宜蘭縣|基隆市|[台臺]北市|新北市|桃園市|新竹市|新竹縣"
middle_regex <- "苗栗縣|[台臺]中市|彰化縣|南投縣|雲林縣"
south_regex <-
  "嘉義市|嘉義縣|[台臺]南[縣市]|高雄市|屏東縣|澎湖縣"
east_regex <- "花蓮縣|台東縣"

currentLevels <- str_replace(currentLevels, 
            north_regex, "北部")
currentLevels <- str_replace(currentLevels, 
            middle_regex, "中部")
currentLevels <- str_replace(currentLevels, 
            south_regex, "南部")
newLevels <- str_replace(currentLevels, 
            east_regex, "東部")


levels(covid19$地區) <- newLevels
covid19$地區
```

```{r}
levels(covid19$`年齡層`)

# 創造10歲間距的所有可能
start <- seq(5, 55, by=10) # 由5到55，每個值差10的數值向量
end <- seq(14, 64, by=10)
middleLevels <- 
  rep(
    paste0(start,"-",end), 
    each=2) # 每個新間距要2個
newLevels <- c("4", middleLevels, "65+", "65+")

levels(covid19$年齡層) <- newLevels
covid19$年齡層
```

```{r}
factor2 <- 
  factor(c("好","好","普通","普通", "好"))
levels(factor2)

factor2[[6]] <- "差"
factor2 # 元素6變NA
```

```{r}
factor2 <- 
  factor(c("好","好","普通","普通", "好"))
levels(factor2)

# 先擴大levels
levels(factor2) <- c(levels(factor2), "差")
levels(factor2)
factor2[[6]] <- "差"
factor2
```

```{r}
levels(covid19$`性別`) <- c("Male", "Female")
levels(covid19$`性別`)
```

```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/od/data/api/EDC3AD26-8AE7-4916-A00B-BC6048D19BF8?$format=json") ->
  garbageRoutes
```

```{r}
str(garbageRoutes)
```

```{r}
install.packages("dplyr")
library(purrr)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
pick_小新 <- example$name == "小新"
data_selected <- 
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )
```

```{r}
map(example, ~.x[pick_小新]) -> 
  data_selected 
  
data_selected
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
map(dance, ~.x$title) ->
  list_titles

View(list_titles)
```

```{r}
# 記載第一個表演的所有場次訊息
dance[[1]]$showInfo
str(dance[[1]]$showInfo)
# 計算第一個表演有幾個場次
length(dance[[1]]$showInfo)
# 計算第二個表演有幾個場次
length(dance[[2]]$showInfo)
```

```{r}
map(dance[[4]]$showInfo, ~ .x$time) ->
  
list_showTimes_dance4
```

```{r}
map(dance[[8]]$showInfo, ~ .x[c("time", "location")]) -> list_showTimesLocation_dance8
print(list_showTimesLocation_dance8)
```

```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/api/datasets/0EE4E6BF-CEE6-4EC8-8FE1-71F544015127/json/preview", simplifyDataFrame = F) -> busRoutes
```

```{r}
busRoutes[[1]][c("Id", "providerId", "providerName", "nameZh")]
busRoutes[[2]][c("Id", "providerId", "providerName", "nameZh")]
map(busRoutes, ~ .x[c("Id", "providerId", "providerName", "nameZh")])
```

```{r}
jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

```{r}
weather_next36hours$cwbopendata$dataset$location$locationName

map(weather_next36hours$cwbopendata$dataset$location$weatherElement, ~ .x$elementName)

map(weather_next36hours$cwbopendata$dataset$location$weatherElement, ~ .x$time[[1]][c("startTime", "endTime")])

map(weather_next36hours$cwbopendata$dataset$location$weatherElement, ~ .x$time[[1]]$parameter$parameterValue)
```













