---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```

```{r}
library(readr)
A02_company_all_public <- read_csv("https://www.dropbox.com/s/rtz2a9na62n3a8l/A02_company_all_public.csv?dl=1")
A02_company_all_public$`候選人` -> candidate
```

```{r}
"我的年紀" = 20
My_age = "我的年紀"
```

```{r}
c("aa", "bb", "cc")
c(1, 25, 77)
```

```{r}
c("小名今年幾歲", 25)
```
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
levels(majors10_factor)
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
typeof(trueInteger)
trueInteger+2
```

```{r}
stringInteger <- c("1", "2", "-11")
class(stringInteger) # 無法進行數值運算
numericInteger<- as.integer(stringInteger)
numericInteger+2
```

```{r}
studentId <- c(410773002, 410773015)
studentId <- as.character(studentId)
class(studentId)
```

```{r}
library(lubridate)
```

```{r}
tpeDateTime <- ymd_hms("2020-03-18 
13:52:40", tz="Asia/Taipei")
tpeDateTime
class(tpeDateTime)
typeof(tpeDateTime)
```

```{r}
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
tz="Europe/Lisbon")
```

```{r}
with_tz(tpeDateTime, tzone="UTC")
with_tz(pgTime, tzone="UTC")
```
```{r}
studentTime <- c(
ymd_hms("2020-03-04T08:15:27Z"), 
ymd_hms("2020-03-18 15:39:53", tz="Asia/Taipei"), 
ymd_hms("2020-03-18 15:39:53", tz="Asia/Taipei"))
studentTime
```
```{r}
vectorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)

print(vectorExample)
print(listExample)
```

```{r}
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list(c("108-1"),
       c("高級會計學","高等統計學")
       ),
  list(c("108-2"),
       c("食在拉丁美洲"))
)
print(`小明108學年課表B`)
```
```{r}
`小明108學年課表D` <- list(
    list(
    semester=c("108-1"),
    courses=c("高級會計學","高等統計學")
       ),
  `下學期`=list(
    semester=c("108-2"),
    c("食在拉丁美洲"))
)
print(`小明108學年課表D`)
```

```{r}
library(lubridate)
commit <- list(
  author = list(
    name = "Martin老師",
    email = "mtlin@gm.ntpu.edu.tw",
    time = ymd_hms("2020-03-25T07:17:40Z")
    ),
  commiter = list(
    name = "emilyluckey",
    email = "emily007@gmail.com",
    time = ymd_hms("2020-03-26T08:18:40Z")
  ),
  message = "update"
)
print(commit)
```

```{r}
browseURL("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") 
```

```{r}
library(jsonlite)
toJSON(commit)
```

```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

```{r}
save(commit, weather_next36hours, `小明108學年課表D`, file = "today.Rda")
```

```{r}
load("today.Rda")
```

```{r}
`小明的修課記錄` <- list(
  name = "小明",
  semesters = list(
    `108-1` = list(
      course1_1081 = list(
        name = "microeconomics",
        teacher = "Alice",
        grade = 85
      ),
      course2_1081 = list(
        name = "macroeconomics",
        teacher = "Mark",
        grade = 78
      )),
      
    `108-2` = list(
      course1_1082 = list(
        name = "作業研究",
        teacher = "Jason",
        grade = 90
      )
    )
  )
)
`小明的修課記錄`
```


```{r}
# 108-1 
course1_1081 <- 
  list(
    name="個體經濟學",
    teacher="Alice",
    grade=85
  )
course2_1081 <-
  list(
    name="總體經濟學",
    teacher="Mark",
    grade=78
  )
`108-1修課記錄` <- 
  list(
    course1_1081,
    course2_1081
  )

# 108-2
course1_1082 <- 
  list(
    name="作業研究",
    teacher="Jason",
    grade=90
  )
`108-2修課記錄` <- 
  list(
    course1_1082
  )

# 整合兩學期
`每學期修課記錄` <- list(
  `108-1`=`108-1修課記錄`,
  `108-2`=`108-2修課記錄`
)

# 完成記錄
`小明的修課記錄` <- 
  list(
    name="小明",
    semesters=`每學期修課記錄`
  )
`小明的修課記錄`
```

```{r}
library(lubridate)
weatherforecast <- list(
    Taipei = list(
      date = list(ymd("2020-03-31"), ymd("2020-04-01")),
      temp = list(highest = 25, lowest = 18)
    ),
    NewTaipei = list(
      date = list(ymd("2020-03-31"), ymd("2020-04-01")),
      temp = list(highest = 24, lowest = 15)
    )
)
weatherforecast
```
































